Add note that a checkout of the repository is required
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

diff --git a/scripts/make-docs b/scripts/make-docs
--- a/scripts/make-docs
+++ b/scripts/make-docs
@@ -187,7 +187,8 @@ POSIX_HERESTRING
   done
   unset IFS
 
-  echo "ERRR: could not find project '${_repo}' in any of the paths in REPOS_PATH ${REPOS_PATH}." >&2
+  echo "ERRR: could not find project '${_repo}' in any of the paths in REPOS_PATH '${REPOS_PATH}'." >&2
+  echo "NOTE: you must have a checkout of '${_repo}' in one of the directories of '${REPOS_PATH}'." >&2
   unset _path _repo
   exit 1
 }
